#!/usr/bin/env bash
set -euo pipefail

# Generated by cp1 during provisioning.
# This joins a worker to the cluster via the control-plane endpoint.

kubeadm join 10.50.0.10:6443 --token n1cf9w.1vf98a2s9vmtejcf --discovery-token-ca-cert-hash sha256:80154922d3d798079283dea54da5dbd1c7adbc6d4c5517fd63fc9edb6a2f1d5b  --cri-socket unix:///run/containerd/containerd.sock
