#!/usr/bin/env bash
set -euo pipefail

CP_IP="${1:-}"
if [[ -z "${CP_IP}" ]]; then
  echo "ERROR: Missing CONTROL_PLANE_IP argument."
  echo "Usage: $0 <CONTROL_PLANE_IP>"
  exit 1
fi

CLUSTER_NAME="${CLUSTER_NAME:-vagrant-k8s}"
#POD_CIDR="${POD_CIDR:-10.244.0.0/16}"
POD_CIDR="${POD_CIDR:-192.168.0.0/16}"
SVC_CIDR="${SVC_CIDR:-10.96.0.0/12}"
K8S_VERSION="${K8S_VERSION:-}"

ARTIFACT_DIR="/vagrant/artifacts"
KUBECONFIG_OUT="${ARTIFACT_DIR}/kubeconfig"
JOIN_OUT="${ARTIFACT_DIR}/join.sh"

echo "[10-controlplane] Starting control-plane bootstrap (CP_IP=${CP_IP})"
mkdir -p "${ARTIFACT_DIR}"

# If rerun, fail fast if cluster already exists
if [[ -f /etc/kubernetes/admin.conf ]]; then
  echo "ERROR: /etc/kubernetes/admin.conf exists. Control-plane appears already initialized."
  echo "If you intend to rebuild: vagrant destroy -f && vagrant up"
  exit 1
fi

echo "[10-controlplane] Writing kubeadm config..."
cat >/root/kubeadm-config.yaml <<EOF
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "${CP_IP}"
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: "${CLUSTER_NAME}"
controlPlaneEndpoint: "${CP_IP}:6443"
networking:
  podSubnet: "${POD_CIDR}"
  serviceSubnet: "${SVC_CIDR}"
EOF

# kubeadm init
echo "[10-controlplane] Running kubeadm init..."
if [[ -n "${K8S_VERSION}" ]]; then
  kubeadm init --config /root/kubeadm-config.yaml --kubernetes-version "${K8S_VERSION}"
else
  kubeadm init --config /root/kubeadm-config.yaml
fi

export KUBECONFIG=/etc/kubernetes/admin.conf
CALICO_VERSION="${CALICO_VERSION:-3.31.2}"

echo "[10-controlplane] Installing Calico (Tigera Operator) v${CALICO_VERSION}..."
kubectl create -f "https://raw.githubusercontent.com/projectcalico/calico/v${CALICO_VERSION}/manifests/operator-crds.yaml"
kubectl create -f "https://raw.githubusercontent.com/projectcalico/calico/v${CALICO_VERSION}/manifests/tigera-operator.yaml"

curl -fsSLo /root/calico-custom-resources.yaml \
  "https://raw.githubusercontent.com/projectcalico/calico/v${CALICO_VERSION}/manifests/custom-resources.yaml"

kubectl create -f /root/calico-custom-resources.yaml

echo "[10-controlplane] Waiting for kube-system pods to appear..."
for _ in {1..60}; do
  if kubectl get pods -n kube-system >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

echo "[10-controlplane] Generating join command..."
JOIN_CMD="$(kubeadm token create --print-join-command)"
cat >"${JOIN_OUT}" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by cp1 during provisioning.
# This joins a worker to the cluster via the control-plane endpoint.

${JOIN_CMD} --cri-socket unix:///run/containerd/containerd.sock
EOF
chmod +x "${JOIN_OUT}"

# --- Export host-usable kubeconfig ---
echo "[10-controlplane] Exporting kubeconfig to ${KUBECONFIG_OUT}..."

cp /etc/kubernetes/admin.conf "${KUBECONFIG_OUT}"
sed -i -E "s#server: https://.*:6443#server: https://${CP_IP}:6443#g" "${KUBECONFIG_OUT}"

chmod 0644 "${KUBECONFIG_OUT}" "${JOIN_OUT}"

echo "[10-controlplane] Installing metrics server"
kubectl apply -f /vagrant/manifests/metrics-server-deployment.yaml

echo "[10 - controlplane] Installing API gateway NGINX Gateway Fabric"

echo "[10-controlplane] Done."
echo "[10-controlplane] Artifacts:"
echo "  - ${JOIN_OUT}"
echo "  - ${KUBECONFIG_OUT}"
echo "[10-control plane] - list available namespaces "
kubectl get namespaces
